# Generated by Django 4.0.4 on 2022-04-12 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField(verbose_name='Артикул')),
                ('start_check', models.DateTimeField(verbose_name='Начало периуда')),
                ('end_check', models.DateTimeField(verbose_name='Конец периода')),
                ('step', models.CharField(choices=[('1h', 'Один час'), ('12h', 'Двенадцать часов'), ('24h', 'Двадцать часов')], max_length=255, verbose_name='Интервал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Названия товара')),
                ('brand', models.CharField(max_length=400, verbose_name='Бренд')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('old_price', models.IntegerField(verbose_name='Цена без скидки')),
                ('date', models.DateTimeField(auto_now=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='tracker.tracker')),
            ],
        ),
    ]
