# Generated by Django 4.0.4 on 2022-04-13 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='tracker.tracker', verbose_name='Трекер'),
        ),
    ]
